name = "forum-api"
main = "worker.js"
compatibility_date = "2026-05-24"

# חיבור למסד הנתונים
[[d1_databases]]
binding = "DB"
database_name = "forum" # שנה לשם מסד הנתונים שיצרת
database_id = "" # יש להעתיק מדאשבורד קלאודפלייר
